---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[postgresql::server]
      - recipe[postgresql::databindery_database]
    attributes:
