---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-14.04

common_attributes: &ATTRIBUTES
    opsworks:
      layers:
        rails-app:
          name: Rails App Server
          id: 33dfd9f0-c9a2-446e-801f-49ba916b3aab
          instances:
            rails-app1:
              public_dns_name: ec2-54-93-221-13.eu-central-1.compute.amazonaws.com
              private_dns_name: ip-172-31-19-31.eu-central-1.compute.internal
              ip: 54.93.221.13
              private_ip: 172.31.19.31
        solr:
          name: Solr
          id: dab71ac5-a146-437e-9377-3d1baee7c19b
          elb-load-balancers: []
          instances: {}
        postgres:
          name: Postgres
          id: 5f6c3401-ebcf-4259-9faf-f236b451f94c
          elb-load-balancers: []
          instances:
            postgres1:
              public_dns_name: ec2-54-93-221-13.eu-central-1.compute.amazonaws.com
              private_dns_name: ip-172-31-19-31.eu-central-1.compute.internal
              ip: 54.93.221.13
              private_ip: 172.31.19.31

    deploy:
      databindery:
        deploy_to: "/srv/www/databindery"
        application: databindery
        environment: {}
        rails_env: production
        database:
          password: banana

suites:
  - name: postgres_setup
    run_list:
      - recipe[databindery::database]
    attributes:
      <<: *ATTRIBUTES

  - name: solr_setup
    run_list:
      - recipe[databindery::solr]
    attributes:
      <<: *ATTRIBUTES
